services:
  fastapi:
    build: .
    environment:
      - REDIS_AUTH_1_URL=redis://${REDIS_AUTH_1_HOST}:${REDIS_AUTH_1_PORT}/${REDIS_AUTH_1_DB}
      - POSTGRES_USER_1_URL="postgres://${POSTGRES_USER_1_USER}:${POSTGRES_USER_1_PASSWORD}@${POSTGRES_USER_1_HOST}:${POSTGRES_USER_1_PORT}/${POSTGRES_USER_1_DB_NAME}?sslmode=disable"
      - POSTGRES_APPEAL_1_URL="postgres://${POSTGRES_APPEAL_1_USER}:${POSTGRES_APPEAL_1_PASSWORD}@${POSTGRES_APPEAL_1_HOST}:${POSTGRES_APPEAL_1_PORT}/${POSTGRES_APPEAL_1_DB_NAME}?sslmode=disable"
    ports:
      - "80:80"


  redis_auth_1:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_AUTH_1_PASSWORD: ${REDIS_AUTH_1_PASSWORD}
    volumes:
      - redis_auth_1_data:/var/lib/redis/data
    command: ["redis-server", "--requirepass", "${REDIS_AUTH_1_PASSWORD}"]



  # postgres_user_1:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_USER_1_DB_NAME}
  #     POSTGRES_USER: ${POSTGRES_USER_1_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_USER_1_PASSWORD}
  #   volumes:
  #     - postgres_user_1_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # mdb:
  #   image: mongo:latest
  #   container_name: mdb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=12345
  #   ports:
  #     - "27017:27017"
  # postgres_appeal_1:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_APPEAL_1_DB_NAME}
  #     POSTGRES_USER: ${POSTGRES_APPEAL_1_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_APPEAL_1_PASSWORD}
  #   volumes:
  #     - postgres_appeal_1_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

  # postgres_message_1:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_MESSAGE_1_DB_NAME}
  #     POSTGRES_USER: ${POSTGRES_MESSAGE_1_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_MESSAGE_1_PASSWORD}
  #   volumes:
  #     - postgres_message_1_data:/var/lib/postgresql/data
  #   ports:
  #     - "5434:5432"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8001:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}  # Email для входа в pgAdmin
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}  # Пароль для pgAdmin
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin  # Хранение данных pgAdmin
  #   container_name: pgadmin

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
  #     ME_CONFIG_MONGODB_URL: ${MONGO_URI}

volumes:
  redis_auth_1_data:
#   postgres_user_1_data:
#   postgres_appeal_1_data:
#   postgres_message_1_data:
#   pgadmin_data:
#   mongodb_data:
